
FROM postgres:15-alpine

ENV POSTGRES_DB=team_bot
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres


COPY migrations/ /docker-entrypoint-initdb.d/


RUN echo "max_connections = 100" >> /usr/local/share/postgresql/postgresql.conf.sample
RUN echo "shared_buffers = 256MB" >> /usr/local/share/postgresql/postgresql.conf.sample

EXPOSE 5432
